name: Sync Images

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  sync_multiarch:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login Harbor2
        uses: docker/login-action@v3.2.0
        with:
          registry: ${{ secrets.HARBOR2_URL }}
          username: ${{ secrets.HARBOR_COMMON_USERNAME }}
          password: ${{ secrets.HARBOR_COMMON_PASSWORD }}

      - name: Retag & Push multiarch images
        run: ./retag-images-multiarch.sh images_multiarch.txt ${{ secrets.HARBOR2_URL }}

  sync_amd64:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login Harbor2
        uses: docker/login-action@v3.2.0
        with:
          registry: ${{ secrets.HARBOR2_URL }}
          username: ${{ secrets.HARBOR_COMMON_USERNAME }}
          password: ${{ secrets.HARBOR_COMMON_PASSWORD }}

      - name: Retag & Push amd64 images
        run: ./retag-images.sh images_amd64.txt ${{ secrets.HARBOR2_URL }}

